In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)

In [3]:
A-B

array([[ 17.        , -14.5       ,  14.33333333, -12.75      ],
       [ 12.5       , -10.66666667,  10.25      ,  -8.8       ],
       [  8.33333333,  -6.75      ,   6.2       ,  -4.83333333],
       [  4.25      ,  -2.8       ,   2.16666667,  -0.85714286]])

In [4]:
print("A@C", C@A)
print("dot", np.dot(A, C))
print("A*C", A*C)

A@C [[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]
dot [[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
A*C [[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]


In [5]:
print("AA**-1", np.round(A@np.linalg.inv(A)))
print("CC**-1", np.round(C@np.linalg.inv(C)))

AA**-1 [[ 1.  0.  0.  0.]
 [ 0.  1. -0.  0.]
 [ 0.  0.  1. -0.]
 [ 0. -0. -0.  1.]]
CC**-1 [[ 1.  0.  0.  0.]
 [-0.  1.  0. -0.]
 [-0.  0.  1. -0.]
 [-0. -0. -0.  1.]]


In [6]:
print(D_inv@E_inv) 
print(np.linalg.inv(E@D))
print(np.linalg.inv(D@E))

[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
[[ 0.21096296 -0.256      -0.1517037 ]
 [-0.15365079  0.20571429  0.56634921]
 [ 0.05367196 -0.28342857  0.12833862]]


In [7]:
A_det = np.linalg.det(A)
B_det = np.linalg.det(B)
C_det = np.linalg.det(C)
print(A_det)
print(B_det)
print(C_det)

1.6534391534393115e-07
0.0
1.0498026371041163e-07


In [8]:
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
C_inv = np.linalg.inv(C)
print(A_inv)
print(B_inv)
print(C_inv)

#if the determinant is equal to 0 then there exists no inverse

LinAlgError: Singular matrix

In [ ]:
print(np.linalg.inv(D).T)
print(np.linalg.inv(D.T))

[[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]]
[[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]]


$$
2x+3y=-1\\
x+y=0
$$
$$
\begin{bmatrix}
2&3 &| &-1\\
1&1 &| &0
\end{bmatrix}
$$
Multiply row 2 with -2 and add to row 1
$$
\begin{bmatrix}
0&1 &| &-1\\
1&1 &| &0
\end{bmatrix}
$$

Multiply row 1 with -1 and add to row 2
$$
\begin{bmatrix}
0&1 &| &-1\\
1&0 &| &1
\end{bmatrix}
$$
Swap row 1 and row 2
$$
\begin{bmatrix}
1&0 &| &1\\
0&1 &| &-1
\end{bmatrix}
$$
$$
x = 1\\
y = -1
$$

$$
x+0y=5\\
0x+y=7
$$
$$
\begin{bmatrix}
1&0 &| &5\\
0&1 &| &7
\end{bmatrix}
$$
$$
x = 5\\
y = 7
$$

$$
x+-3y+3z=0.5\\
x-5y+3z=0.5\\
4x-6y+6z=1
$$

$$
\begin{bmatrix}
1&-3&3 &| &0.5\\
1&-5&3 &| &0.5\\
4&-6&6 &| &1
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&-3&3 &| &0.5\\
0&-2&0 &| &0\\
4&-6&6 &| &1
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&-3&3 &| &0.5\\
0&-2&0 &| &0\\
0&6&-6 &| &-1
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&-3&3 &| &0.5\\
0&1&0 &| &0\\
0&6&-6 &| &-1
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&-3&3 &| &0.5\\
0&1&0 &| &0\\
0&0&-6 &| &-1
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&-3&3 &| &0.5\\
0&1&0 &| &0\\
0&0&1 &| &1/6
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&0&3 &| &0.5\\
0&1&0 &| &0\\
0&0&1 &| &1/6
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&0&0 &| &0\\
0&1&0 &| &0\\
0&0&1 &| &1/6
\end{bmatrix}
$$

$$
2x+3y+4z=2\\
x+y+4z=-2\\
2x+5y+4z=3
$$
$$
\begin{bmatrix}
2&3&4 &| &2\\
1&1&4 &| &-2\\
2&5&4 &| &3
\end{bmatrix}
$$
$$
\begin{bmatrix}
2&3&4 &| &2\\
0&-0.5&2 &| &-3\\
2&5&4 &| &3
\end{bmatrix}
$$
$$
\begin{bmatrix}
2&3&4 &| &2\\
0&-0.5&2 &| &-3\\
0&2&0 &| &1
\end{bmatrix}
$$
$$
\begin{bmatrix}
2&3&4 &| &2\\
0&-0.5&2 &| &-3\\
0&0&8 &| &-11
\end{bmatrix}
$$
$$
\begin{bmatrix}
2&3&4 &| &2\\
0&-0.5&2 &| &-3\\
0&0&1 &| &-11/8
\end{bmatrix}
$$
$$
\begin{bmatrix}
2&3&4 &| &2\\
0&-0.5&0 &| &-0.25\\
0&0&1 &| &-11/8
\end{bmatrix}
$$
$$
\begin{bmatrix}
2&3&4 &| &2\\
0&1&0 &| &0.5\\
0&0&1 &| &-11/8
\end{bmatrix}
$$
$$
\begin{bmatrix}
2&0&4 &| &0.5\\
0&1&0 &| &0.5\\
0&0&1 &| &-11/8
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&0&2 &| &0.25\\
0&1&0 &| &0.5\\
0&0&1 &| &-11/8
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&0&0 &| &3\\
0&1&0 &| &0.5\\
0&0&1 &| &-11/8
\end{bmatrix}
$$


In [ ]:
A = np.array([
    [2, 3, 4],
    [1, 1, 4],
    [2, 5, 4]
], dtype=float)
B = np.array([2, -2, 3], dtype=float)
np.linalg.solve(A, B)

array([ 3.   ,  0.5  , -1.375])

$$
x+y+z=2\\
2x+2y+2z=-2\\
3x+3y+3z=3
$$

$$
\begin{bmatrix}
1&1&1 &| &2\\
2&2&2 &| &-2\\
3&3&3 &| &3\\
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&1&1 &| &2\\
0&0&0 &| &-4\\
3&3&3 &| &3\\
\end{bmatrix}
$$
$$
\begin{bmatrix}
1&1&1 &| &2\\
0&0&0 &| &-4\\
0&0&0 &| &-3\\
\end{bmatrix}
$$
Cannot be solved

In [ ]:
A = np.array([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]
], dtype=float)
B = np.array([2, -2, 3], dtype=float)
np.linalg.solve(A, B)

array([-1.80143985e+16, -3.60287970e+16,  5.40431955e+16])

In [ ]:
def dotp(a, b):
    assert len(a) == len(b)
    return sum([i * j for (i, j) in zip(a, b)])

def dim(a):
    rows = len(a)
    if rows == 0:
        return [0, 0]
    return [rows, len(a[0])]


def col(idx, a):
    _, cols = dim(a)
    assert cols > idx
    return [row[idx] for row in a]

def row(idx, a):
    rows, _ = dim(a)
    assert rows > idx
    return a[idx]

def matmul(a, b):
    a_rows, a_cols = dim(a)
    b_rows, b_cols = dim(b)
    assert a_rows == b_cols
    return [[dotp(row(i, a), col(j, b)) for j in range(b_cols)] for i in range(a_rows)]


ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

print(matmul(ma, mb))

np_ma = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

np_mb = np.array([
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
])

print(np.linalg.matmul(np_ma, np_mb))

[[33, 6, 26], [78, 21, 77], [123, 36, 128]]
[[ 33   6  26]
 [ 78  21  77]
 [123  36 128]]
